@startuml

interface Edificio
{
    +visitarEdificio: void
}

interface EdificioConPista
{
    - visita : Visita 
    +visitarEdificio : void
}
class EdificioSinPista
{
    +visittarEdificio():void
    -buscarLadron(): void
}

class Biblioteca
{
    -pista :Pista
}

class Banco
{
    -pista :Pista
}

class Aeropuerto
{
    -pista :Pista
}
class Puerto
{
    -pista :Pista
}
class Bolsa
{
    -pista :Pista
}

EdificioConPista<|.. Bolsa
EdificioConPista<|.. Banco
EdificioConPista<|.. Aeropuerto
EdificioConPista<|.. Puerto
EdificioConPista<|.. Biblioteca

Edificio <|... EdificioConPista
Edificio <|..EdificioSinPista


@enduml