@startuml

interface Edificio
{
    +visitarEdificio: void
}
class EdificioConMaton
{
    +visitar(Policia policia): Amenaza
}
class EdificioConLadron
{
    +visitar((Policia policia): RespuestaDelEventos
}

class Biblioteca
{
    -pista :Pista
}

class Banco
{
    -pista :Pista
}

class Aeropuerto
{
    -pista :Pista
}
class Puerto
{
    -pista :Pista
}
class Bolsa
{
    -pista :Pista
}

class EdificioConPista
{
    +visitar(Policia policia): Pista
}
EdificioConPista<|-- Bolsa
EdificioConPista<|-- Banco
EdificioConPista<|-- Aeropuerto
EdificioConPista<|-- Puerto
EdificioConPista<|-- Biblioteca

Edificio <|... EdificioConLadron
Edificio <|... EdificioConMaton
Edificio <|... EdificioConPista


@enduml