@startuml
class AlgoThieft
{
    -pistas : List<Pista>
    -policia : List<Policia>
    -edificio : List<Edificio>
    -ciudades : List<Ciudad>
    -ladrones : List<Ladron>
    -dossierLadrones: DossierLadrones
    -objetosRobados: List<ObjetoRobado>
    -estrategiasDeEscape: List<EstrategiasDeEscape>
}

class Partida
{
    - ciudadActual: Ciudad
    - reloj : Reloj
    - ladron : Ladron
    - objetoRobado : ObjetoRobado
    - estrategiasDeEscape: EstrategiaDeEscape

    +pedirOrdenDeCaptura(): void
    +viajarA() : void
    +entrarA(): void
}
AlgoThieft --> Partida

@enduml