@startuml
class AlgoThieft
{

    -ciudades : List<Ciudad>
    -ladrones : List<Ladron>
    + iniciarPartida(nombre:String)
    + nuveoCaso()
}

class Partida
{
    - ladron:Ladron
    - policia:Policia
    - ciudades:List<Ciudad>
    - ciudadesNoConectadas:List<Ciudad>
    - pistasPorCiudad: Dicctionary
    - ciudadActual:Ciudad 
    - ciudadAnterior:Ciudad 
    - buscador:BuscadorLadrones 


    + obtenerTiempoDeViaje(ciudad:Ciudad):Int
    + partidaTerminada()
    + reiniciarCiudades()
    + viajar(ciudad:Ciudad)
    - obtenerCiudadRandom():Ciudad
    - obtenerRutaLadron()
}
AlgoThieft --> Partida

@enduml