@startuml
class Maton
{
 + obtenerDemoraPorArma():int
}

interface Arma
{
}

class Cuchillo
{
}
class Pistola
{
}

class Ladron
{
}
interface Orden
{
    + tengoOrdenDeCaptura(Ladron ladron) : void
}
class OrdenDeCaptura
{
    + tengoOrdenDeCaptura(Ladron ladron) : void
}
class OrdenDeCapturaInvalida
{
    + tengoOrdenDeCaptura(Ladron ladron) : void
}
Orden <|.. OrdenDeCaptura
Orden <|.. OrdenDeCapturaInvalida
Maton --> Arma
Arma <|.. Cuchillo
Arma <|.. Pistola
Ladron --> Orden
@enduml