@startuml
class Maton
{
 + atacar(policia:Policia): IRespuestaDelEvento
}

interface Arma
{
    + herir(policia:Policia): IRespuestaDelEvento
}

class Cuchillo
{
    + herir(policia:Policia): Amenaza
}
class Pistola
{
    + herir(policia:Policia): Amenaza
}

class Ladron
{
    -nombre:String 
    -sexo:String 
    -hobby:String 
    -pelo:String 
    -auto:String 
    -caracteristica:String 
    -pistasLadron:List<Pista> 
    -rutaDeEscape:IRutaDeEscape 
    + entregarse():IRespuestaDelEvento
    + escapar():IRespuestaDelEvento
    +obtenerRutaEscape():IRutaDeEscape
}
interface IOrdenDeCaptura
{
    + capturar(ladron:Ladron):IRespuestaDelEvento
}
class OrdenDeCaptura
{
    + capturar(ladron:Ladron):IRespuestaDelEvento
}
class OrdenDeCapturaInvalida
{
    + capturar(ladron:Ladron):LadronEscapo
}
IOrdenDeCaptura <|.. OrdenDeCaptura
IOrdenDeCaptura <|.. OrdenDeCapturaInvalida
Maton --> Arma
Arma <|.. Cuchillo
Arma <|.. Pistola
IOrdenDeCaptura --> Ladron
@enduml