@startuml
/'class Pistas
{
    -edificio : Edificio
    -ciudad : Ciudad
    -pista : string
}

class Dificultad
{
}
class Facil
{
}
class Medio
{
}
class Dificil
{
}'/

interface Pista
{
    -pista: string
    +obtenerRespuesta: string
}
class PistaFacil
{
    +obtenerRespuesta: string
}

class PistaMedia
{
    +obtenerRespuesta: string
}

class PistaDificil
{
    +obtenerRespuesta: string
}


Pista <|.. PistaFacil
Pista <|.. PistaMedia
Pista <|..PistaDificil

@enduml