@startuml
class Policia
{
    - int casosResueltos
    + amenaza(Maton maton): Amenaza
    + demorar(int demora): void
}
interface Rango
{
    + rangoSiguiente(int casosResueltos): Rango
    +dificultad(): Dificultad
}

class Detective
{
    -int tiempoDeViaje
}
class Novato
{
    -int tiempoDeViaje
}
class Sargento
{
    -int tiempoDeViaje
}
class Investigador
{
    -int tiempoDeViaje
}

interface Dificultad
{
}

Policia -->Rango
Rango <|..Investigador
Rango <|..Sargento
Rango <|.. Detective
Rango <|..Novato
Rango ...> Dificultad
@enduml