@startuml
class Policia
{
    - nombre:String 
    - casosResueltos:Int 
    - rango:IRango 
    - orden:IOrdenDeCaptura 
    - reloj:Reloj 
    + viajarDesdeHasta(ciudad:Ciudad, otraCiudad:Ciudad)
    + demorar(demora:Int)
    + dormir()
    + investigascionInterpol()
    + nuevoCasoResuelto()
    + detener(ladron:Ladron):IRespuestaDelEvento
    + recibirOrdenDeCaptura(orden:IOrdenDeCaptura)

}
interface IRango
{
    + {abstract} obtenerRango(casosResueltos:Int):IRango
    + {abstract} obtenerPistaPorRango(): Dicctionary
    + {abstract} tiempoDeViaje(ciudad:Ciudad, otraCiudad:Ciudad):Int
    + {abstract} obtenerRutaDeEscapeSegunRango():IRutaDeEscape
}

class Detective
{
    -int tiempoDeViaje
    + obtenerRutaDeEscapeSegunRango():RutaNormal
}
class Novato
{
    -int tiempoDeViaje
    + obtenerRutaDeEscapeSegunRango():RutaFacil
}
class Sargento
{
    -int tiempoDeViaje
    + obtenerRutaDeEscapeSegunRango():RutaDificil
}
class Investigador
{
    -int tiempoDeViaje
    + obtenerRutaDeEscapeSegunRango():RutaNormal
}


Policia -->IRango
IRango <|..Investigador
IRango <|..Sargento
IRango <|.. Detective
IRango <|..Novato

@enduml