@startuml

interface RutaDeEscape
{
    +cantPaises():int
}
class RutaFacil
{
    +cantPaises(): int
}
class RutaMedioDificil
{
    +cantPaises():int
}
class RutaDificil
{
    +cantPaises():int
}

RutaDeEscape <|... RutaFacil
RutaDeEscape <|... RutaMedioDificil
RutaDeEscape <|... RutaDificil
@enduml