@startuml

interface IRutaDeEscape
{
    + devolverProximaCiudad():Ciudad
    + crearRuta(List<Ciudad> ciudades)
    + ciudadEnLaRuta(ciudad:Ciudad):Boolean
    + devolverCiudadActual():Ciudad
}
class RutaFacil
{
    
}
class RutaMedioDificil
{
    
}
class RutaDificil
{
    
}

IRutaDeEscape <|... RutaFacil
IRutaDeEscape <|... RutaMedioDificil
IRutaDeEscape <|... RutaDificil

@enduml